<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { useWanziStore } from '../../stores/wanzi'
import WanziPet from './WanziPet.vue'
const store = useWanziStore(); const root=ref<HTMLElement|null>(null); const composer=ref(''); const showClearConfirm=ref(false); const dragging=ref(false); const dragMoved=ref(false); const suppressOrbClick=ref(false); const dragOffset=ref({x:0,y:0}); const dragStart=ref({x:0,y:0}); const stageClass=computed(()=>`wanzi-stage-${store.stage}`)
function clampPosition(x:number,y:number){const width=store.stage==='chat'?440:store.stage==='pet'?400:150;const height=store.stage==='chat'?525:store.stage==='pet'?290:150;return{x:Math.min(Math.max(width/2,x),window.innerWidth-width/2),y:Math.min(Math.max(height/2,y),window.innerHeight-height/2)}}
function startDrag(event:PointerEvent){const target=event.target as HTMLElement;if(target?.closest('input,.wanzi-composer button,.wanzi-header-btn,.wanzi-back,.wanzi-confirm,.wanzi-pet-model'))return;const box=root.value?.getBoundingClientRect();if(!box)return;dragging.value=true;dragMoved.value=false;dragStart.value={x:event.clientX,y:event.clientY};dragOffset.value={x:event.clientX-(box.left+box.width/2),y:event.clientY-(box.top+box.height/2)};window.addEventListener('pointermove',moveDrag);window.addEventListener('pointerup',stopDrag,{once:true})}
function moveDrag(event:PointerEvent){if(!dragging.value)return;if(Math.abs(event.clientX-dragStart.value.x)+Math.abs(event.clientY-dragStart.value.y)>4)dragMoved.value=true;store.setPosition(clampPosition(event.clientX-dragOffset.value.x,event.clientY-dragOffset.value.y))} function stopDrag(){if(dragMoved.value){suppressOrbClick.value=true;window.setTimeout(()=>suppressOrbClick.value=false,0)}dragging.value=false;window.removeEventListener('pointermove',moveDrag)} function activateOrb(){if(!suppressOrbClick.value)store.openPet()} function focusComposer(){nextTick(()=>document.querySelector<HTMLInputElement>('.wanzi-chat-input')?.focus())} async function send(){const text=composer.value;composer.value='';await store.sendMessage(text);focusComposer()} async function confirmClear(){await store.clearHistory();showClearConfirm.value=false} function onResize(){if(store.position)store.setPosition(clampPosition(store.position.x,store.position.y))}
watch(()=>store.stage,()=>nextTick(()=>onResize()))
onMounted(()=>{window.addEventListener('resize',onResize);if(!store.position)store.setPosition(clampPosition(window.innerWidth-86,window.innerHeight-88))});onUnmounted(()=>{stopDrag();window.removeEventListener('resize',onResize)})
</script>
<template><div ref="root" class="wanzi-floating" :class="[stageClass,{dragging}]" :style="store.position?{left:`${store.position.x}px`,top:`${store.position.y}px`}:undefined" @pointerdown="startDrag"><button v-if="store.stage==='orb'" class="wanzi-orb" data-testid="wanzi-orb" aria-label="点击唤醒烷仔" title="点击唤醒烷仔" @click.stop="activateOrb"><span class="orb-core"/></button><section v-else-if="store.stage==='pet'" class="wanzi-pet-stage" data-testid="wanzi-pet" aria-label="3D烷仔"><div class="wanzi-greeting">{{store.greeting}}</div><WanziPet class="wanzi-pet-model" @click="store.openChat"/><span class="wanzi-pet-tip">拖动旋转 · 单击聊天</span><button class="wanzi-back" aria-label="收回悬浮球" title="收回悬浮球" @click.stop="store.restoreOrb">×</button></section><section v-else class="wanzi-chat-stage" data-testid="wanzi-chat" aria-label="与烷仔对话"><WanziPet class="wanzi-chat-model" :interactive="false"/><div class="wanzi-chat-panel"><header class="wanzi-chat-header"><span class="wanzi-online"/><strong>与烷仔对话</strong><button class="wanzi-header-btn" aria-label="清空对话" title="清空对话" @click.stop="showClearConfirm=true">↻</button><button class="wanzi-header-btn" aria-label="收起聊天" title="收起聊天" @click.stop="store.closeChat">−</button></header><div class="wanzi-messages" aria-live="polite"><div v-if="!store.hasMessages" class="wanzi-empty">你好，我是烷仔。可以问我污水处理工艺、甲烷排放、减排建议或网站使用方法。</div><div v-for="(message,index) in store.messages" :key="`${message.timestamp}-${index}`" class="wanzi-message" :class="message.role"><div class="wanzi-bubble">{{message.content}}</div></div></div><div v-if="store.sending" class="wanzi-thinking">烷仔正在思考……</div><form class="wanzi-composer" @submit.prevent="send"><input v-model="composer" class="wanzi-chat-input" maxlength="1000" autocomplete="off" placeholder="输入你的问题…" :disabled="store.sending" aria-label="输入你的问题"/><button type="submit" :disabled="store.sending||!composer.trim()">发送</button></form></div><div v-if="showClearConfirm" class="wanzi-confirm" role="dialog" aria-label="确认清空对话"><p>确定清空当前对话吗？</p><button @click="confirmClear">确认</button><button @click="showClearConfirm=false">取消</button></div></section></div></template>
