from .schemas import FormulaRecord, QualityStatus


FORMULAS = [
    FormulaRecord(
        formula_id="VP-WATER-001",
        name="离散水量守恒",
        expression="V(t+Δt)=clip(V(t)+(Qin-Qout)×Δt/1440, 0, Vmax)",
        variables={"V": "单元储水量(m³)", "Qin": "入流(m³/d)", "Qout": "出流(m³/d)", "Δt": "仿真步长(min)", "Vmax": "有效容积(m³)"},
        units="m³",
        scope="所有水线工艺单元的演示级状态传播",
        source_type="engineering_identity",
        full_source=None,
        source_locator=None,
        trust_status=QualityStatus.PROVISIONAL,
        requires_plant_calibration=True,
        implementation="backend/app/simulation/mass_balance.py:advance_volume",
        tests="backend/tests/test_simulation.py:test_water_balance_and_level_bounds",
    ),
    FormulaRecord(
        formula_id="VP-QUALITY-001",
        name="完全混合守恒传播",
        expression="Cmix=(V×C+Vin×Cin)/(V+Vin)",
        variables={"Cmix": "混合后浓度", "V": "原储量", "C": "原浓度", "Vin": "步内入水量", "Cin": "入水浓度"},
        units="各指标采用 mg/L；pH 与温度仅作状态插值",
        scope="V1无反应、无经验去除率的演示传播",
        source_type="unverified_software_assumption",
        trust_status=QualityStatus.AWAITING_SOURCE,
        requires_plant_calibration=True,
        implementation="backend/app/simulation/mass_balance.py:mix_quality",
        tests="backend/tests/test_simulation.py:test_quality_is_provisional_and_propagates",
    ),
    FormulaRecord(
        formula_id="VP-ENERGY-001",
        name="设备演示能耗",
        expression="E=Prated×load×Δt/60",
        variables={"E": "步内电耗(kWh)", "Prated": "示范额定功率(kW)", "load": "设定值归一化负荷", "Δt": "分钟"},
        units="kWh",
        scope="无厂家性能曲线时的界面与状态闭环",
        source_type="illustrative_relationship",
        trust_status=QualityStatus.AWAITING_CALIBRATION,
        requires_plant_calibration=True,
        implementation="backend/app/simulation/equipment.py:advance_equipment",
        tests="backend/tests/test_simulation.py:test_equipment_state_changes_energy",
    ),
    FormulaRecord(
        formula_id="VP-DO-001",
        name="曝气设定与DO演示关系",
        expression="DO(t+Δt)=clip(DO+0.03×blower_load-0.015, 0, 10)",
        variables={"DO": "溶解氧(mg/L)", "blower_load": "鼓风机归一化负荷"},
        units="mg/L/step",
        scope="好氧池与MBR膜池的操作反馈演示；不是ASM机理模型",
        source_type="illustrative_relationship",
        trust_status=QualityStatus.AWAITING_CALIBRATION,
        requires_plant_calibration=True,
        implementation="backend/app/simulation/engine.py:_apply_process_demonstration",
        tests="backend/tests/test_simulation.py:test_blower_fault_changes_do_and_alarm",
    ),
    FormulaRecord(
        formula_id="VP-CH4-001",
        name="甲烷风险分级",
        expression="normal<1; attention<2; high<4; critical≥4 (mg/L)",
        variables={"CH4": "示范甲烷浓度或估算状态(mg/L)"},
        units="mg/L",
        scope="仅用于V1可视风险分级，不用于合规或排放核算",
        source_type="unverified_demo_threshold",
        trust_status=QualityStatus.AWAITING_SOURCE,
        requires_plant_calibration=True,
        implementation="backend/app/simulation/methane.py:risk_level",
        tests="backend/tests/test_simulation.py:test_methane_anomaly_scenario",
    ),
]
